name: "Test stage"

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string


jobs:
  test-unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Install Poetry"
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: "Install dependencies"
        shell: bash
        run: make dependencies
      - name: "Run unit test suite"
        shell: bash
        run: make test-unit
      - name: "Upload unit test results"
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: unit-test-results
          path: test-artefacts/
          retention-days: 30
      - name: "Publish unit test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86  # v2.4
        with:
          paths: test-artefacts/unit-tests.xml

  sonarcloud-analysis:
    name: "SonarCloud Analysis"
    needs: [test-unit]
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Full history is needed for better analysis
      - name: "Download unit test coverage report"
        uses: actions/download-artifact@v6
        with:
          name: unit-test-results
          path: test-artefacts/
      - name: "SonarCloud Scan"
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANISATION_KEY }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.python.coverage.reportPaths=test-artefacts/coverage.xml
